### ISSUE TITLE
Moonraker restart loop

### ISSUE THREAD

**Issue by aguinaldoabbj** [mkuf/prind#58]
Hi all,

Firstly, congrats on this promising initiative.

I'm trying to get the prind stack up but the moonraker container starts in a restart loop.

docker logs shows:

```
prind-moonraker-1  | [utils.py:setup_logging()] - config_file: cfg/moonraker.cfg
prind-moonraker-1  | [utils.py:setup_logging()] - startup_warnings: []
prind-moonraker-1  | [utils.py:setup_logging()] - log_file: /tmp/moonraker.log
prind-moonraker-1  | [utils.py:setup_logging()] - software_version: ?
prind-moonraker-1  | [utils.py:setup_logging()] - python_version: 3.10.7 (main, Sep 13 2022, 03:02:33) [GCC 10.2.1 20210110]
prind-moonraker-1  | [moonraker.py:main()] - Server Config Error
prind-moonraker-1  | Traceback (most recent call last):
prind-moonraker-1  |   File "/opt/moonraker/moonraker/confighelper.py", line 924, in _parse_file
prind-moonraker-1  |     stat = file_path.stat()
prind-moonraker-1  |   File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
prind-moonraker-1  |     return self._accessor.stat(self, follow_symlinks=follow_symlinks)
prind-moonraker-1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/cfg/moonraker.cfg'
prind-moonraker-1  | 
prind-moonraker-1  | The above exception was the direct cause of the following exception:
prind-moonraker-1  | 
prind-moonraker-1  | Traceback (most recent call last):
prind-moonraker-1  |   File "/opt/moonraker/moonraker/moonraker.py", line 460, in main
prind-moonraker-1  |     server = Server(app_args, file_logger, event_loop)
prind-moonraker-1  |   File "/opt/moonraker/moonraker/moonraker.py", line 67, in __init__
prind-moonraker-1  |     self.config = config = self._parse_config()
prind-moonraker-1  |   File "/opt/moonraker/moonraker/moonraker.py", line 129, in _parse_config
prind-moonraker-1  |     config = confighelper.get_configuration(self, self.app_args)
prind-moonraker-1  |   File "/opt/moonraker/moonraker/confighelper.py", line 1040, in get_configuration
prind-moonraker-1  |     source.read_file(start_path)
prind-moonraker-1  |   File "/opt/moonraker/moonraker/confighelper.py", line 1028, in read_file
prind-moonraker-1  |     self._parse_file(main_conf, [])
prind-moonraker-1  |   File "/opt/moonraker/moonraker/confighelper.py", line 1013, in _parse_file
prind-moonraker-1  |     raise ConfigError(
prind-moonraker-1  | confighelper.ConfigError: Configuration File Not Found: '/opt/cfg/moonraker.cfg''
prind-moonraker-1  | [moonraker.py:main()] - Server Shutdown
prind-moonraker-1 exited with code 1
```

Howerver I didn't made any change in prind file structure, moonraker.cfg is located at config/ directory and I can see the volume mappings in docker-compose.yml. 

Any clues?

**Comment by aguinaldoabbj** [comment]
Edit: Nevermind. Removed all images, volumes, restarted everything again and now all stack containers are up!
